### ISSUE TITLE
[Question] Advantages of react-query over swr

### ISSUE THREAD

**Issue by olivierobert** [pakaponk/gsr-scraping#19]
## Issue

The client application leverages `react-query` to hydrate the UI. Since the application is built with Next.JS, what do you think of the advantages of using `react-query` over Vercel's own solution 👉  [swr.vercel.app](https://swr.vercel.app/)?

**Comment by pakaponk** [comment]
To be honest, I haven't spent the time researching on the Pros and Cons of `swr` and `react-query`.
`react-query` is the library that I gave a try first and am happy with it so I haven't tried `swr` yet.

Upon looking into [the feature comparison provided by React Query](https://tanstack.com/query/v4/docs/comparison)
Generally, the difference between these two libraries lay in their advanced features which I haven't got the chance to use yet. Although from that document, it is clearly seen that React Query provides more features but I think we should research them ourselves if we have a need for those features since the document might be biased.

Anyway, In my opinion, the clear benefit of using `react-query` is it also supports other frameworks such as Vue and Solid so if we decide to change those frameworks, the learning curve is less than having to learn how to use the new library. (Keep in mind though that there might be other libraries for those frameworks that are significantly better than `react-query`.

On the other hand, the `swr` is smaller and it is supported by the Vercel team so there might be some optimizations specifically for Next.js. Although the second advantage is waived when using  the`swr` with other bundlers such as Vite or Create React App.

**Comment by olivierobert** [comment]
All good points 😀 `swr` does have a simple caching strategy IMO since it is based on a unique key value and the `fetcher` param plays nice with `axios` or any other custom utility that makes it easier to set up IMO too.
